-- Wklej to w Supabase: Project -> SQL Editor -> New query -> Run

create table visits (
  id bigint generated by default as identity primary key,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone default now()
);

-- Wyłączamy Row Level Security dla prostoty (ruch trafia tylko przez nasz backend z kluczem service_role)
alter table visits enable row level security;

create policy "Allow insert from service role"
on visits for insert
to service_role
with check (true);
